# Generated by Django 4.2.1 on 2023-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainer_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
