# Generated by Django 4.2.1 on 2023-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trainee_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
