# Generated by Django 4.2.1 on 2023-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='muscle_name',
            field=models.CharField(choices=[('Pec_Mayori', 'Pec Mayori'), ('Oblique', 'Oblique'), ('Neck', 'Neck'), ('Deltoids_Front', 'Deltoids Front'), ('GROINS', 'GROINS'), ('QUADS', 'QUADS'), ('knee', 'knee'), ('Brachii_short_Head', 'Brachii short Head'), ('Tibialis_Anterior', 'Tibialis Anterior'), ('shin', 'shin'), ('Brachioradialis', 'Brachioradialis'), ('Abdominis', 'Abdominis'), ('Digitorum', 'Digitorum'), ('Brachii_Long_Head', 'Brachii Long Head'), ('CALVES', 'CALVES'), ('PERONEALS', 'PERONEALS'), ('Trapezius', 'Trapezius'), ('Deltoids_Back', 'Deltoids Back'), ('Latissimus_Dorsi', 'Latissimus Dorsi'), ('Triceps_Lateral', 'Triceps Lateral'), ('Triceps_Medial', 'Triceps Medial'), ('Erector_Spinae', 'Erector Spinae'), ('Extensor_Digitorum', 'Extensor Digitorum'), ('Flexor_Carpi', 'Flexor Carpi'), ('GLUTES', 'GLUTES')], max_length=100),
        ),
    ]
