# Generated by Django 4.2.1 on 2023-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tutorial_muscle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tutorial_videos/'),
        ),
    ]
