# Generated by Django 4.2.1 on 2023-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_tutorial_muscle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='muscle_name',
            field=models.CharField(choices=[('PecMayori', 'Pec Mayori'), ('Oblique', 'Oblique'), ('Neck', 'Neck'), ('Deltoids_Front', 'Deltoids Front'), ('GROINS', 'GROINS'), ('QUADS', 'QUADS'), ('knee', 'knee'), ('Brachii_short_Head', 'Brachii short Head'), ('Tibialis_Anterior', 'Tibialis Anterior'), ('shin', 'shin'), ('Brachioradialis', 'Brachioradialis'), ('Abdominis', 'Abdominis'), ('Digitorum', 'Digitorum'), ('Brachii_Long_Head', 'Brachii Long Head'), ('CALVES', 'CALVES'), ('PERONEALS', 'PERONEALS'), ('Trapezius', 'Trapezius'), ('Deltoids_Back', 'Deltoids Back'), ('Latissimus_Dorsi', 'Latissimus Dorsi'), ('TricepsMedial', 'Triceps Medial'), ('ErectorSpinae', 'Erector Spinae'), ('ExtensorDigitorum', 'Extensor Digitorum'), ('FlexorCarpi', 'Flexor Carpi'), ('GLUTES', 'GLUTES'), ('TricepsLateral', 'Triceps Lateral')], max_length=100),
        ),
    ]
