# Generated by Django 4.2.1 on 2023-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='trainer_images/'),
        ),
    ]
